# Builds shadertest/harness.cpp out of the real PS4 renderer sources, so the host-side shader
# test exercises exactly the code that ships (templates + formula generation).
import os, re

# <workspace>/ps4port/tests/shadertest -> <workspace>
ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..', '..'))
LUS = os.path.join(ROOT, 'Shipwright', 'libultraship')


def read(p):
    return open(p, encoding='utf-8').read()


interp_h = read(os.path.join(LUS, 'include', 'fast', 'interpreter.h'))
interp_cpp = read(os.path.join(LUS, 'src', 'fast', 'interpreter.cpp'))
gl = read(os.path.join(LUS, 'src', 'fast', 'backends', 'gfx_opengl_ps4.cpp'))


def between(s, a, b, include_b=False):
    i = s.index(a)
    j = s.index(b, i)
    return s[i:j + (len(b) if include_b else 0)]


enums = between(interp_h, 'enum {\n    SHADER_0', '#define SHADER_OPT(opt)') + \
    '#define SHADER_OPT(opt) ((uint64_t)(1 << static_cast<int>(ShaderOpts::opt)))\n#endif\n'
ccfeatures = between(interp_h, 'struct CCFeatures {', '};', True)
get_features = between(interp_cpp, 'void gfx_cc_get_features(', 'extern "C" int gfx_create_framebuffer')
formula = between(gl, '#define RAND_NOISE', 'std::optional<std::string> opengl_include_fs')
build_fs = between(gl, 'std::string GfxRenderingAPIOGL::BuildFsShader', 'static size_t numFloats = 0;')
build_vs = between(gl, 'static size_t numFloats = 0;', 'static void Ps4LogShaderSource')

build_fs = build_fs.replace('std::string GfxRenderingAPIOGL::BuildFsShader(const CCFeatures& cc_features)',
                            'std::string BuildFsShader(const CCFeatures& cc_features, bool mSrgbMode, FilteringMode mCurrentFilterMode)')
build_fs = build_fs.replace('    processor.bind_include_loader(opengl_include_fs);\n', '')
build_vs = build_vs.replace('    processor.bind_include_loader(opengl_include_fs);\n', '')
assert 'opengl_include_fs' not in build_fs + build_vs

out = '''// GENERATED by gen_harness.py - do not edit.
#define __PS4__ 1
#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <fstream>
#include <map>
#include <optional>
#include <random>
#include <set>
#include <string>
#include <variant>
#include <vector>
#include <prism/processor.h>
#include "fast/backends/gfx_opengl_ps4_shaders.h"
using namespace Fast;
enum FilteringMode { FILTER_THREE_POINT, FILTER_LINEAR, FILTER_NONE };
''' + enums + '\n' + ccfeatures + '\n' + get_features + '\n' + formula + '\n' + build_fs + '\n' + build_vs + '''
static void Dump(const std::string& dir, std::map<std::string, int>& seen, const std::string& text, const char* ext) {
    if (seen.count(text)) {
        return;
    }
    int id = (int)seen.size();
    seen[text] = id;
    char name[512];
    snprintf(name, sizeof(name), "%s/s%05d.%s", dir.c_str(), id, ext);
    std::ofstream f(name, std::ios::binary);
    f << text;
}

int main(int argc, char** argv) {
    const std::string dir = argc > 1 ? argv[1] : "out";
    const int count = argc > 2 ? atoi(argv[2]) : 3000;
    std::map<std::string, int> seenVs, seenFs;
    std::mt19937_64 rng(1234);
    int generated = 0;

    for (int n = 0; n < count; n++) {
        uint64_t id0 = 0;
        // Each of the 16 combiner slots holds one of the 15 SHADER_* items.
        for (int k = 0; k < 16; k++) {
            // Only the items the combiner generator knows about (inputs 5-7 are never emitted).
            static const uint64_t kItems[] = { SHADER_0, SHADER_INPUT_1, SHADER_INPUT_2, SHADER_INPUT_3, SHADER_INPUT_4,
                                               SHADER_TEXEL0, SHADER_TEXEL0A, SHADER_TEXEL1, SHADER_TEXEL1A, SHADER_1,
                                               SHADER_COMBINED, SHADER_NOISE };
            uint64_t item = kItems[rng() % 12];
            // Bias towards the simple combiners real display lists use.
            if (rng() % 3 == 0) item = 0;
            id0 |= item << (k * 4);
        }
        uint32_t id1 = (uint32_t)(rng() & 0xFFFF);
        if (n % 4 == 0) id1 &= ~(uint32_t)(SHADER_OPT(TEXEL0_MASK) | SHADER_OPT(TEXEL1_MASK) | SHADER_OPT(TEXEL0_BLEND) | SHADER_OPT(TEXEL1_BLEND));
        if (!(id1 & SHADER_OPT(_2CYC))) id0 &= 0xFFFFFFFFull;

        CCFeatures features{};
        gfx_cc_get_features(id0, id1, &features);

        const bool srgb = (n % 7) == 0;
        const FilteringMode filter = (FilteringMode)(n % 3);
        std::string fs = BuildFsShader(features, srgb, filter);
        std::string vs = BuildVsShader(features);
        Dump(dir, seenFs, fs, "frag");
        Dump(dir, seenVs, vs, "vert");
        generated++;
    }
    printf("%d combinations -> %zu fragment, %zu vertex shaders\\n", generated, seenFs.size(), seenVs.size());
    return 0;
}
'''
open(os.path.join(os.path.dirname(__file__), 'harness.cpp'), 'w', encoding='utf-8', newline='\n').write(out)
print('harness.cpp written')
